[package]
name = "pass-secret-service"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.155"
tokio = { version = "1.38.1", features = ["fs", "rt", "rt-multi-thread", "macros", "process"] }
zbus = { version = "4.3.1", default-features = false, features = ["tokio"] }
