name: Build and Release

on:
  push:
    tags:
      - "v*.*"

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: write
    strategy:
      matrix:
        runner: [ubuntu-latest, ubuntu-24.04-arm]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --release
      - name: Rename binary
        run: |
          mkdir -p dist
          cp target/release/pass-secret-service dist/pass-secret-service-$(uname -m)
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/pass-secret-service-*
